defaults:
  - denoiser

name: dit

time_embedding:
# LightningDiT uses continuous timesteps between 0 and 1, but flipped
  scale: -1
  shift: 1

block:
  attention:
    qk_norm: null
  feed_forward:
    name: lightningdit_swiglu
  mlp_ratio: 2.667  # 8/3
  norm_layer:
    name: rms

out_layer:
  norm:
    name: rms

rel_pos_embedding:
  name: rotary
