name: kl_image
scaling_factor: 0.2325
checkpoint_path: ./pretrained/autoencoder/kl_16.pt
architecture:
  down_block_types:
    - DownEncoderBlock2D
    - DownEncoderBlock2D
    - DownEncoderBlock2D
    - DownEncoderBlock2D
    - AttnDownEncoderBlock2D
  up_block_types:
    - AttnUpDecoderBlock2D
    - UpDecoderBlock2D
    - UpDecoderBlock2D
    - UpDecoderBlock2D
    - UpDecoderBlock2D
  block_out_channels: [128, 128, 256, 256, 512]
  layers_per_block: 2
  latent_channels: 16