name: counting_polygons_ffhq
root: null 
labeler_name: null # explicit, ambiguous or None
are_nums_on_images: false
data_shape: [128, 128]
subset_size: null
min_vertices: 2
max_vertices: 9
hsv_saturation: 1.0
hsv_value: 0.9
augment: false
use_stars: true

counting_polygons_classifier_path: null
counting_polygons_classifier_model_base: "resnet50"

subdataset_cfg:
  root: null
  data_shape: [3, 128, 128]
  subset_size: null
  augment: true
